# Generated by Django 5.2 on 2025-04-10 16:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('type_of_project', models.CharField(choices=[('Residential', 'Residential'), ('Commercial', 'Commercial')], max_length=50)),
                ('name_of_property', models.CharField(max_length=100)),
                ('area_of_property_located', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('amenities', models.TextField()),
                ('price', models.FloatField()),
                ('negotiable', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=50)),
                ('display_image', models.ImageField(default=None, null=True, upload_to='projects/display_image/')),
            ],
        ),
        migrations.CreateModel(
            name='Upcoming',
            fields=[
                ('upcoming_project_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('type_of_project', models.CharField(choices=[('Residential', 'Residential'), ('Commercial', 'Commercial'), ('Residential and Commercial', 'Residential and Commercial')], max_length=50)),
                ('name_of_project', models.CharField(max_length=100)),
                ('area_of_project_located', models.CharField(max_length=20)),
                ('builder_name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('amenities', models.TextField()),
                ('rera_no', models.CharField(max_length=50)),
                ('total_area_of_project', models.CharField(max_length=50)),
                ('floor_plan', models.FileField(default=None, null=True, upload_to='files')),
                ('brochure', models.FileField(default=None, null=True, upload_to='files')),
                ('display_image', models.ImageField(default=None, null=True, upload_to='upcoming/display_image/')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=100)),
                ('service_description', models.TextField()),
                ('service_fee', models.DecimalField(decimal_places=2, max_digits=8)),
                ('date', models.DateTimeField()),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/images/')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app.project')),
            ],
        ),
        migrations.CreateModel(
            name='UpcomingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='upcoming/images/')),
                ('upcoming_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app.upcoming')),
            ],
        ),
    ]
