# Generated by Django 5.1.7 on 2025-03-21 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='project',
            fields=[
                ('project_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('type_of_project', models.CharField(choices=[('Residential', 'Residential'), ('Commercial', 'Commercial')], max_length=50)),
                ('name_of_property', models.CharField(max_length=100)),
                ('area_of_property_located', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('amenities', models.TextField()),
                ('price', models.FloatField()),
                ('negotiable', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=50)),
                ('images', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='upcoming',
            fields=[
                ('upcoming_project_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('type_of_project', models.CharField(choices=[('Residential', 'Residential'), ('Commercial', 'Commercial'), ('Residential and Commercial', 'Residential and Commercial')], max_length=50)),
                ('name_of_project', models.CharField(max_length=100)),
                ('area_of_project_located', models.CharField(max_length=20)),
                ('builder_name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('amenities', models.TextField()),
                ('rera_no', models.CharField(max_length=50)),
                ('total_area_of_project', models.CharField(max_length=50)),
                ('images', models.ImageField(upload_to='images')),
                ('floor_plan', models.FileField(default=None, null=True, upload_to='files')),
                ('brochure', models.FileField(default=None, null=True, upload_to='files')),
            ],
        ),
    ]
