# Generated by Django 5.1.7 on 2025-03-21 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='images',
        ),
        migrations.RemoveField(
            model_name='upcoming',
            name='brochure',
        ),
        migrations.RemoveField(
            model_name='upcoming',
            name='floor_plan',
        ),
        migrations.RemoveField(
            model_name='upcoming',
            name='images',
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/images/')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app.project')),
            ],
        ),
        migrations.CreateModel(
            name='UpcomingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='upcoming/images/')),
                ('upcoming_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app.upcoming')),
            ],
        ),
    ]
