# Generated by Django 5.2 on 2025-04-11 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_contactmessage_alter_appointment_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmessage',
            name='submitted_at',
        ),
    ]
