# Generated by Django 5.1.7 on 2025-03-25 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_project_images_remove_upcoming_brochure_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='display_image',
            field=models.ImageField(default=None, null=True, upload_to='projects/display_image/'),
        ),
        migrations.AddField(
            model_name='upcoming',
            name='brochure',
            field=models.FileField(default=None, null=True, upload_to='files'),
        ),
        migrations.AddField(
            model_name='upcoming',
            name='display_image',
            field=models.ImageField(default=None, null=True, upload_to='upcoming/display_image/'),
        ),
        migrations.AddField(
            model_name='upcoming',
            name='floor_plan',
            field=models.FileField(default=None, null=True, upload_to='files'),
        ),
    ]
